In [2]:
import torch

In [5]:
print(f"torch version: {torch.__version__}")

torch version: 1.13.1


In [ ]:
if torch.backends.mps.is_available() and torch.backends.mps.is_built():
    print("✅ Using Apple MPS (Metal Performance Shaders)")
    device = torch.device("mps")
elif torch.cuda.is_available():
    print(f"✅ Using CUDA (GPU): {torch.cuda.get_device_name(0)}")
    device = torch.device("cuda")
else:
    print("⚠️ No GPU available. Using CPU.")
    device = torch.device("cpu")

print(f"device is: {device}")

✅ Using Apple MPS (Metal Performance Shaders)
device is: mps


In [ ]:
# Empty torch
"""
Dosen't allocate any values in the tensor, just showing whatever was in the memory before. Having
zeros is just because maybe that memory didn't have anything to begin with
"""
a = torch.empty(2, 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
# Check type
type(a)

torch.Tensor

In [13]:
torch.zeros(2,3), torch.ones(2,3), torch.rand(2,3)

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0.6473, 0.9318, 0.7871],
         [0.4015, 0.0531, 0.3143]]))

In [15]:
# for reproducability we can use seed
torch.manual_seed(1)
torch.rand(2,3)

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])

In [16]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
torch.arange(0,10,2), torch.linspace(0,10,3), torch.eye(6), torch.full((2,3), 2)

(tensor([0, 2, 4, 6, 8]),
 tensor([ 0.,  5., 10.]),
 tensor([[1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 1.]]),
 tensor([[2, 2, 2],
         [2, 2, 2]]))

In [32]:
# Shape of tensors
a = torch.tensor([[1,2,3],[4,5,6]])
a.shape, a.dtype

(torch.Size([2, 3]), torch.int64)

In [27]:
torch.empty_like(a), torch.ones_like(a), torch.zeros_like(a)

(tensor([[0, 0, 0],
         [0, 0, 0]]),
 tensor([[1, 1, 1],
         [1, 1, 1]]),
 tensor([[0, 0, 0],
         [0, 0, 0]]))

In [ ]:
torch.rand_like(a)
'''
the torch function rand_like is not implemented for Long/int type (which is dtype of a). So need
to change it's dtype to float or double.
'''

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [35]:
b = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.double)
torch.rand_like(b)

tensor([[0.7182, 0.3845, 0.0898],
        [0.1175, 0.6402, 0.1968]], dtype=torch.float64)

In [36]:
# To convert dtype of a tensor
a.to(dtype=torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
'''
vars(torch): gives all the attributes/functions of torch/any class passed as argument.
quint are for quantized
'''
dtypes = {key:val for key, val in vars(torch).items() if isinstance(val, torch.dtype)}
dtypes

{'uint8': torch.uint8,
 'int8': torch.int8,
 'int16': torch.int16,
 'short': torch.int16,
 'int32': torch.int32,
 'int': torch.int32,
 'int64': torch.int64,
 'long': torch.int64,
 'float16': torch.float16,
 'half': torch.float16,
 'float32': torch.float32,
 'float': torch.float32,
 'float64': torch.float64,
 'double': torch.float64,
 'complex32': torch.complex32,
 'chalf': torch.complex32,
 'complex64': torch.complex64,
 'cfloat': torch.complex64,
 'complex128': torch.complex128,
 'cdouble': torch.complex128,
 'bool': torch.bool,
 'qint8': torch.qint8,
 'quint8': torch.quint8,
 'qint32': torch.qint32,
 'bfloat16': torch.bfloat16,
 'quint4x2': torch.quint4x2,
 'quint2x4': torch.quint2x4}

In [ ]:
# Mathematical operations
a = torch.full((2,3), 10)
# scalar operations
a, a+2, a-2, a*2, a/3, a//3

(tensor([[10, 10, 10],
         [10, 10, 10]]),
 tensor([[12, 12, 12],
         [12, 12, 12]]),
 tensor([[8, 8, 8],
         [8, 8, 8]]),
 tensor([[20, 20, 20],
         [20, 20, 20]]),
 tensor([[3.3333, 3.3333, 3.3333],
         [3.3333, 3.3333, 3.3333]]),
 tensor([[3, 3, 3],
         [3, 3, 3]]))

In [52]:
# Elementwise operations
b = torch.full((2,3), 5)
a+b, a-b, a*b, a/b, a**b, a%b

(tensor([[15, 15, 15],
         [15, 15, 15]]),
 tensor([[5, 5, 5],
         [5, 5, 5]]),
 tensor([[50, 50, 50],
         [50, 50, 50]]),
 tensor([[2., 2., 2.],
         [2., 2., 2.]]),
 tensor([[100000, 100000, 100000],
         [100000, 100000, 100000]]),
 tensor([[0, 0, 0],
         [0, 0, 0]]))

In [ ]:
# operations on single tensor
a = torch.randn((3,4))
a, torch.abs(a), torch.round(a), torch.ceil(a), torch.floor(a), torch.clamp(a, min=-0.1, max=0.4)

(tensor([[-0.6331,  0.8795, -0.6842,  0.4533],
         [ 0.2912, -0.8317, -0.5525,  0.6355],
         [-0.3968, -0.6571, -1.6428,  0.9803]]),
 tensor([[0.6331, 0.8795, 0.6842, 0.4533],
         [0.2912, 0.8317, 0.5525, 0.6355],
         [0.3968, 0.6571, 1.6428, 0.9803]]),
 tensor([[-1.,  1., -1.,  0.],
         [ 0., -1., -1.,  1.],
         [-0., -1., -2.,  1.]]),
 tensor([[-0.,  1., -0.,  1.],
         [ 1., -0., -0.,  1.],
         [-0., -0., -1.,  1.]]),
 tensor([[-1.,  0., -1.,  0.],
         [ 0., -1., -1.,  0.],
         [-1., -1., -2.,  0.]]),
 tensor([[-0.1000,  0.4000, -0.1000,  0.4000],
         [ 0.2912, -0.1000, -0.1000,  0.4000],
         [-0.1000, -0.1000, -0.1000,  0.4000]]))

In [74]:
# Tensor reduction
torch.manual_seed(1)
a = torch.randint(0, 5, (3,4), dtype=torch.float)
a, torch.sum(a), torch.sum(a, dim=1, keepdim=True), torch.sum(a, dim=0, keepdim=True), torch.mean(a),\
    torch.mean(a, dim=1, keepdim=True), torch.median(a), torch.max(a), torch.min(a), torch.prod(a),\
    torch.std(a), torch.var(a), torch.argmax(a), torch.argmin(a)


(tensor([[0., 4., 4., 3.],
         [3., 3., 1., 1.],
         [4., 2., 3., 4.]]),
 tensor(32.),
 tensor([[11.],
         [ 8.],
         [13.]]),
 tensor([[7., 9., 8., 8.]]),
 tensor(2.6667),
 tensor([[2.7500],
         [2.0000],
         [3.2500]]),
 tensor(3.),
 tensor(4.),
 tensor(0.),
 tensor(0.),
 tensor(1.3707),
 tensor(1.8788),
 tensor(1),
 tensor(0))

In [ ]:
# matrix operations
a = torch.randint(0, 5, (3,4), dtype=torch.float)
b = torch.randint(5, 10, (4,3), dtype=torch.float)
# matrix multiplications
a, b, torch.matmul(a,b)

(tensor([[1., 3., 3., 0.],
         [2., 1., 2., 1.],
         [0., 3., 1., 4.]]),
 tensor([[8., 6., 9.],
         [7., 9., 9.],
         [8., 6., 7.],
         [8., 7., 8.]]),
 tensor([[53., 51., 57.],
         [47., 40., 49.],
         [61., 61., 66.]]))

In [77]:
a = torch.randint(0, 5, (3,4), dtype=torch.float)
b = torch.randint(5, 10, (3,4), dtype=torch.float)
# dot product
a, b, a*b

(tensor([[3., 1., 2., 0.],
         [0., 4., 0., 3.],
         [3., 0., 3., 4.]]),
 tensor([[6., 9., 9., 5.],
         [8., 5., 6., 8.],
         [6., 9., 7., 8.]]),
 tensor([[18.,  9., 18.,  0.],
         [ 0., 20.,  0., 24.],
         [18.,  0., 21., 32.]]))

In [79]:
# Transpose
a.T, a.transpose(0,1)

(tensor([[3., 0., 3.],
         [1., 4., 0.],
         [2., 0., 3.],
         [0., 3., 4.]]),
 tensor([[3., 0., 3.],
         [1., 4., 0.],
         [2., 0., 3.],
         [0., 3., 4.]]))

In [ ]:
# determinant, inverse of sq matrix: torch.det(a), torch.inverse(a)

In [ ]:
# comparison operations
a = torch.randint(0, 10, (3,4), dtype=torch.float)
b = torch.randint(0, 10, (3,4), dtype=torch.float)
a, b, a > b, a<b, a==b

(tensor([[2., 1., 9., 7.],
         [9., 9., 3., 4.],
         [2., 1., 9., 6.]]),
 tensor([[8., 9., 8., 8.],
         [6., 7., 9., 9.],
         [1., 7., 2., 5.]]),
 tensor([[False, False,  True, False],
         [ True,  True, False, False],
         [ True, False,  True,  True]]),
 tensor([[ True,  True, False,  True],
         [False, False,  True,  True],
         [False,  True, False, False]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [ ]:
# Special functions
a = torch.randint(0, 10, (3,4), dtype=torch.float)
torch.log(a), torch.exp(a), torch.sqrt(a), torch.sigmoid(a), torch.softmax(a, dim=0), torch.relu(a)

(tensor([[2.1972, 0.0000,   -inf, 1.3863],
         [0.0000, 2.1972, 1.0986, 1.7918],
         [0.6931, 1.3863, 2.0794, 1.7918]]),
 tensor([[8.1031e+03, 2.7183e+00, 1.0000e+00, 5.4598e+01],
         [2.7183e+00, 8.1031e+03, 2.0086e+01, 4.0343e+02],
         [7.3891e+00, 5.4598e+01, 2.9810e+03, 4.0343e+02]]),
 tensor([[3.0000, 1.0000, 0.0000, 2.0000],
         [1.0000, 3.0000, 1.7321, 2.4495],
         [1.4142, 2.0000, 2.8284, 2.4495]]),
 tensor([[0.9999, 0.7311, 0.5000, 0.9820],
         [0.7311, 0.9999, 0.9526, 0.9975],
         [0.8808, 0.9820, 0.9997, 0.9975]]),
 tensor([[9.9875e-01, 3.3311e-04, 3.3311e-04, 6.3379e-02],
         [3.3504e-04, 9.9298e-01, 6.6906e-03, 4.6831e-01],
         [9.1075e-04, 6.6906e-03, 9.9298e-01, 4.6831e-01]]),
 tensor([[9., 1., 0., 4.],
         [1., 9., 3., 6.],
         [2., 4., 8., 6.]]))

In [ ]:
# Inplace operations

'''
When we have very large tensors we would not want to create a new tensor. But be cautious because
in backpropgation it could break things.
a += b (inplace, can break backprop)
a = a+b (not inplace, creates new tensor a and won't break backprop)
to do inplace operations just append '_' to the operators/functions. Supported by most operators/functions.
'''
a = torch.randint(0, 10, (3,4), dtype=torch.float)
b = torch.randint(-10, 10, (3,4), dtype=torch.float)
print(a,"\n" ,b)
print(a.add_(b),"\n" , a,"\n" , b.relu_())

tensor([[8., 1., 2., 6.],
        [5., 3., 9., 1.],
        [5., 6., 2., 6.]]) 
 tensor([[ -3.,   2.,   3.,  -9.],
        [  0.,   3.,  -3.,   4.],
        [  6.,   3.,  -5., -10.]])
tensor([[ 5.,  3.,  5., -3.],
        [ 5.,  6.,  6.,  5.],
        [11.,  9., -3., -4.]]) 
 tensor([[ 5.,  3.,  5., -3.],
        [ 5.,  6.,  6.,  5.],
        [11.,  9., -3., -4.]]) 
 tensor([[0., 2., 3., 0.],
        [0., 3., 0., 4.],
        [6., 3., 0., 0.]])


In [101]:
# Copy tensor
a = torch.randint(0, 10, (3,4), dtype=torch.float)
b = a # (not this, b is also changed if a is changed as b is just a reference to a)
id(a), id(b) # both pointing to same location in memory

(5070111952, 5070111952)

In [102]:
b = a.clone()
id(a), id(b)

(5070111952, 5070390096)

In [108]:
# Moving existing tensor to gpu
a = torch.randn(10000,10000, device=torch.device('cpu'))
b = torch.randn(10000,10000, device=torch.device('cpu'))

In [107]:
import time

In [109]:
# On cpu
start = time.time()
torch.matmul(a,b)
print(f"time taken in sec: {time.time() - start}")

time taken in sec: 47.13321614265442


In [110]:
a = a.to(device=torch.device('mps'))
b = b.to(device=torch.device('mps'))

In [111]:
# On apple gpu
start = time.time()
torch.matmul(a,b)
print(f"time taken in sec: {time.time() - start}")

time taken in sec: 0.44126200675964355


In [ ]:
"""
Drastic difference in time taken to multiply the two tensors on cpu and gpu
"""

In [115]:
# Reshaping Tensors
a = torch.arange(0,24)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [118]:
b = a.reshape(2,4,3)
b, a

(tensor([[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8],
          [ 9, 10, 11]],
 
         [[12, 13, 14],
          [15, 16, 17],
          [18, 19, 20],
          [21, 22, 23]]]),
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23]))

In [ ]:
b.flatten()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [123]:
b.permute(2,0,1), b.permute(2,0,1).shape

(tensor([[[ 0,  3,  6,  9],
          [12, 15, 18, 21]],
 
         [[ 1,  4,  7, 10],
          [13, 16, 19, 22]],
 
         [[ 2,  5,  8, 11],
          [14, 17, 20, 23]]]),
 torch.Size([3, 2, 4]))

In [128]:
b.shape, b.unsqueeze(0), b.unsqueeze(0).shape

(torch.Size([2, 4, 3]),
 tensor([[[[ 0,  1,  2],
           [ 3,  4,  5],
           [ 6,  7,  8],
           [ 9, 10, 11]],
 
          [[12, 13, 14],
           [15, 16, 17],
           [18, 19, 20],
           [21, 22, 23]]]]),
 torch.Size([1, 2, 4, 3]))

In [134]:
b.shape, b.squeeze(0), b.unsqueeze(0).shape, b.unsqueeze(0).squeeze(0).shape

(torch.Size([2, 4, 3]),
 tensor([[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8],
          [ 9, 10, 11]],
 
         [[12, 13, 14],
          [15, 16, 17],
          [18, 19, 20],
          [21, 22, 23]]]),
 torch.Size([1, 2, 4, 3]),
 torch.Size([2, 4, 3]))

In [138]:
# convert tensor to numpy array and vice versa
import numpy as np
a = np.array([1,2,3])
b = torch.tensor([4,5,6])
torch.from_numpy(a), b.numpy()

(tensor([1, 2, 3]), array([4, 5, 6]))